version: 2.1

jobs:
  tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: exit 1
      
   tests-1:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: exit 0
      
   tests-1:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: exit 0
      
workflows:
  tests:
    jobs:
      - tests
